import { test } from "node:test";
import assert from "node:assert/strict";
import {
  deriveWorkerBindings,
  emitWorkerBindings,
  scanModelWorkers,
  byModelPath,
  type WorkerIo,
} from "./worker-io.ts";

test("byModelPath is a spec-compliant comparator: returns 0 for equal paths", () => {
  assert.equal(byModelPath({ path: "a" }, { path: "a" }), 0);
  assert.equal(byModelPath({ path: "a" }, { path: "b" }), -1);
  assert.equal(byModelPath({ path: "b" }, { path: "a" }), 1);
  // Antisymmetry (the property the old `? -1 : 1` form violated for equal paths).
  const eq = [{ path: "x" }, { path: "x" }];
  assert.equal(byModelPath(eq[0], eq[1]) + byModelPath(eq[1], eq[0]), 0);
});

const XML = `<?xml version="1.0"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"
                  xmlns:zeebe="http://camunda.org/schema/zeebe/1.0">
  <bpmn:process id="orders">
    <bpmn:serviceTask id="Charge" name="Charge card">
      <bpmn:extensionElements>
        <zeebe:taskDefinition type="orders.charge" />
        <zeebe:ioMapping>
          <zeebe:property name="io.nanobpm.dataEnvelope.in" value="Payment" />
          <zeebe:property name="io.nanobpm.dataEnvelope.out" value="Receipt" />
        </zeebe:ioMapping>
      </bpmn:extensionElements>
    </bpmn:serviceTask>
    <bpmn:serviceTask id="Notify">
      <bpmn:extensionElements>
        <zeebe:taskDefinition type="orders.notify" />
      </bpmn:extensionElements>
    </bpmn:serviceTask>
  </bpmn:process>
</bpmn:definitions>`;

test("scanModelWorkers extracts task type, element id, process, and envelope io", () => {
  const w = scanModelWorkers(XML);
  const charge = w.find((x) => x.taskType === "orders.charge") as WorkerIo;
  assert.ok(charge);
  assert.equal(charge.elementId, "Charge");
  assert.equal(charge.process, "orders");
  assert.equal(charge.in, "Payment");
  assert.equal(charge.out, "Receipt");
  const notify = w.find((x) => x.taskType === "orders.notify") as WorkerIo;
  assert.equal(notify.in, undefined);
  assert.equal(notify.out, undefined);
});

test("emitWorkerBindings matches the console format (union + DomainTypes refs)", () => {
  const out = emitWorkerBindings(
    [{ taskType: "orders.charge", inputType: "Payment", outputType: "Receipt" }],
    ["Payment", "Receipt"],
  );
  assert.match(out, /AUTO-GENERATED by nanobpmn from the App manifest \(ADR 0033 §3\)/);
  assert.match(out, /import type \{ DomainTypes \} from ".\/domain-rows.d.ts";/);
  assert.match(out, /export type WorkerTaskType = "orders.charge";/);
  assert.match(out, /export interface WorkerInputs \{\n {2}"orders.charge": DomainTypes\["Payment"\];\n\}/);
  assert.match(out, /export interface WorkerOutputs \{\n {2}"orders.charge": DomainTypes\["Receipt"\];\n\}/);
});

test("emitWorkerBindings falls back to string union + no import when nothing is declared", () => {
  const out = emitWorkerBindings([{ taskType: "orders.notify" }], []);
  assert.match(out, /export type WorkerTaskType = "orders.notify";/);
  assert.doesNotMatch(out, /import type \{ DomainTypes \}/);
  assert.match(out, /export interface WorkerInputs \{\}/);
});

test("deriveWorkerBindings is deterministic and emits worker-io.d.ts", () => {
  const models = [{ path: "processes/orders.bpmn", xml: XML }];
  const a1 = deriveWorkerBindings(models, ["Payment", "Receipt"]);
  const a2 = deriveWorkerBindings(models, ["Payment", "Receipt"]);
  assert.deepEqual(a1, a2);
  assert.equal(a1[0].path, "nano-generated/worker-io.d.ts");
  assert.match(a1[0].content, /"orders.charge": DomainTypes\["Payment"\]/);
});

test("a service task without a task definition is ignored", () => {
  const xml = `<bpmn:process id="p"><bpmn:serviceTask id="X"></bpmn:serviceTask></bpmn:process>`;
  assert.deepEqual(scanModelWorkers(xml), []);
});
